# Generated by Django 5.1.5 on 2025-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTargeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(unique=True)),
                ('meta_location', models.CharField(max_length=100)),
                ('interests', models.JSONField(default=list)),
                ('education_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('columnas_usadas', models.TextField()),
                ('pesos_columnas', models.TextField()),
                ('archivo_modelo', models.FileField(upload_to='media/modelos/')),
            ],
        ),
    ]
