# Generated by Django 5.1.5 on 2025-05-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('columnas_usadas', models.JSONField()),
                ('pesos_columnas', models.TextField()),
                ('archivo_modelo', models.FileField(upload_to='media/modelos/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterTargeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('meta_location', models.CharField(blank=True, max_length=100, null=True)),
                ('interests', models.JSONField(blank=True, default=list, null=True)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('modelo_clustering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clustering.modeloentrenado')),
            ],
        ),
    ]
