# Generated by Django 5.1.5 on 2025-05-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloentrenado',
            name='nombre',
            field=models.TextField(default='modelo'),
            preserve_default=False,
        ),
    ]
