# Generated by Django 5.1.5 on 2025-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0002_modeloentrenado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloentrenado',
            name='descripcion',
            field=models.TextField(default='modelo de prueba'),
            preserve_default=False,
        ),
    ]
