# Generated by Django 5.1.5 on 2025-05-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0003_modeloentrenado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloentrenado',
            name='columnas_usadas',
            field=models.JSONField(),
        ),
    ]
