# Generated by Django 5.1.5 on 2025-05-23 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0004_alter_modeloentrenado_columnas_usadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clustertargeting',
            name='cluster_id',
        ),
        migrations.AddField(
            model_name='clustertargeting',
            name='age_max',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clustertargeting',
            name='age_min',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clustertargeting',
            name='cluster',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clustertargeting',
            name='modelo_clustering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clustering.modeloentrenado'),
        ),
    ]
