# Generated by Django 5.1.5 on 2025-05-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0005_remove_clustertargeting_cluster_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertargeting',
            name='age_max',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clustertargeting',
            name='age_min',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clustertargeting',
            name='education_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clustertargeting',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clustertargeting',
            name='meta_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
