# Generated by Django 5.1.5 on 2025-05-23 08:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clustering', '0007_alter_clustertargeting_age_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, default='', max_length=255)),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('objective', models.CharField(choices=[('CONVERSIONS', 'Conversiones'), ('POST_ENGAGEMENT', 'Interacción'), ('BRAND_AWARENESS', 'Conocimiento de marca'), ('LEAD_GENERATION', 'Leads')], default='REACH', max_length=250)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_id', models.CharField(blank=True, max_length=100)),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('call_to_action', models.CharField(choices=[('LEARN_MORE', 'Más información'), ('SIGN_UP', 'Registrarse'), ('SHOP_NOW', 'Comprar ahora'), ('CONTACT_US', 'Contáctanos'), ('SUBSCRIBE', 'Suscribirse'), ('GET_OFFER', 'Obtener oferta')], max_length=50)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(blank=True, max_length=100)),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('billing_event', models.CharField(blank=True, choices=[('IMPRESSIONS', 'CPM (Por cada 1000 impresiones)'), ('CLICKS', 'CPC (Por cada click)'), ('LINK_CLICKS', 'Clicks en enlaces específicos'), ('POST_ENGAGEMENT', 'Interacciones'), ('VIDEO_VIEWS', 'Vistas de video')], default='REACH', max_length=250)),
                ('optimization_goal', models.CharField(blank=True, choices=[('IMPRESSIONS', 'Conversiones'), ('REACH', 'Alcance'), ('POST_ENGAGEMENT', 'Engagement con el post'), ('VIDEO_VIEWS', 'Vistas'), ('IMPRESSIONS', 'Impresiones'), ('LEAD_GENERATION', 'Leads'), ('CONVERSIONS', 'Conversiones'), ('VALUE', 'Value'), ('LANDING_PAGE_VIEWS', 'Landing page')], default='REACH', max_length=250)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('targeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clustering.clustertargeting')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiserTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='administrador.advertisertiktok')),
            ],
        ),
        migrations.CreateModel(
            name='AdGroupTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('segmentacion', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adgroups', to='administrador.campaigntiktok')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='Pendiente', max_length=20)),
                ('comentario_admin', models.TextField(blank=True, help_text='Comentario del administrador al aprobar o rechazar', null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('texto', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.revision')),
            ],
        ),
        migrations.CreateModel(
            name='AdTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tiktok_ads_images/')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PUBLICADO', 'Publicado')], default='PENDIENTE', max_length=20)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('adgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='administrador.adgrouptiktok')),
                ('revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(blank=True, max_length=100)),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('adset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.adset')),
                ('creative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.creative')),
                ('revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacante', models.CharField(max_length=255)),
                ('empresa', models.TextField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('contrato', models.CharField(max_length=100)),
                ('salario', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('industria', models.CharField(choices=[('TECNOLOGIA', 'Tecnología e Informática'), ('SALUD', 'Salud y Medicina'), ('EDUCACION', 'Educación'), ('INGENIERIA', 'Ingeniería y Manufactura'), ('VENTAS', 'Ventas y Marketing'), ('ADMINISTRACION', 'Administración y Negocios'), ('LEGAL', 'Legal'), ('LOGISTICA', 'Logística y Transporte'), ('SERVICIOS', 'Servicios Generales'), ('TURISMO', 'Turismo y Hospitalidad'), ('ENTRETENIMIENTO', 'Artes, Medios y Entretenimiento'), ('INVESTIGACION', 'Ciencia e Investigación'), ('AGROINDUSTRIA', 'Agroindustria y Medio Ambiente')], max_length=100, null=True)),
                ('modalidad', models.CharField(choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], max_length=50, null=True)),
                ('experiencia', models.CharField(max_length=100, null=True)),
                ('grupo', models.IntegerField(blank=True, null=True)),
                ('modelo_clustering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clustering.modeloentrenado')),
            ],
        ),
    ]
