# Generated by Django 5.1.5 on 2025-03-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('addset_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('creative', models.CharField(max_length=250)),
                ('acces_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addset_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('campaign_id', models.CharField(max_length=250)),
                ('daily_budjet', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('acces_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('red_social', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('publico_objetivo', models.TextField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('formato_anuncio', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
