# Generated by Django 5.1.5 on 2025-05-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('CONVERSIONS', 'Conversiones'), ('POST_ENGAGEMENT', 'Interacción'), ('BRAND_AWARENESS', 'Conocimiento de marca'), ('LEAD_GENERATION', 'Leads')], default='REACH', max_length=250),
        ),
        migrations.AlterField(
            model_name='revision',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
