# Generated by Django 5.1.5 on 2025-03-20 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='formato_anuncio',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, default='Brand Awareness', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado')], default='active', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='hashtags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='nombre',
            field=models.CharField(default='Nueva Campaña', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='publico_objetivo',
            field=models.TextField(blank=True, default='Público general', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='red_social',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], default='facebook', max_length=20),
        ),
    ]
