# Generated by Django 5.1.5 on 2025-05-22 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroupTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('segmentacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('adgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='administrador.adgrouptiktok')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiserTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='administrador.advertisertiktok')),
            ],
        ),
        migrations.AddField(
            model_name='adgrouptiktok',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adgroups', to='administrador.campaigntiktok'),
        ),
    ]
