# Generated by Django 5.1.6 on 2025-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='plataforma',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50),
        ),
        migrations.AddField(
            model_name='adset',
            name='plataforma',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='plataforma',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50),
        ),
        migrations.AddField(
            model_name='creative',
            name='plataforma',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=50),
        ),
    ]
