# Generated by Django 5.1.5 on 2025-05-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_adgrouptiktok_adtiktok_advertisertiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtiktok',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tiktok_ads_images/'),
        ),
    ]
