# Generated by Django 5.1.5 on 2025-05-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_campaign_objective_alter_revision_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='experiencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='grupo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='industria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='modalidad',
            field=models.CharField(choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], max_length=50, null=True),
        ),
    ]
