# Generated by Django 5.1.5 on 2025-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_campaign_formato_anuncio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='publico_objetivo',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='formato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, choices=[('conversiones', 'Conversiones'), ('interacciones', 'Interacción'), ('alcance', 'Alcance')], default='Brand Awareness', max_length=250),
        ),
    ]
