# Generated by Django 5.1.5 on 2025-05-23 01:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_adtiktok_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtiktok',
            name='comentario_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adtiktok',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='adtiktok',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PUBLICADO', 'Publicado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='adtiktok',
            name='revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.revision'),
        ),
        migrations.AddField(
            model_name='adtiktok',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
