# Generated by Django 5.1.5 on 2025-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_vacante_experiencia_vacante_grupo_vacante_industria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='vacante',
            name='industria',
            field=models.CharField(choices=[('TECNOLOGIA', 'Tecnología e Informática'), ('SALUD', 'Salud y Medicina'), ('EDUCACION', 'Educación'), ('INGENIERIA', 'Ingeniería y Manufactura'), ('VENTAS', 'Ventas y Marketing'), ('ADMINISTRACION', 'Administración y Negocios'), ('LEGAL', 'Legal'), ('LOGISTICA', 'Logística y Transporte'), ('SERVICIOS', 'Servicios Generales'), ('TURISMO', 'Turismo y Hospitalidad'), ('ENTRETENIMIENTO', 'Artes, Medios y Entretenimiento'), ('INVESTIGACION', 'Ciencia e Investigación'), ('AGROINDUSTRIA', 'Agroindustria y Medio Ambiente')], max_length=100, null=True),
        ),
    ]
