# Generated by Django 5.1.5 on 2025-05-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_ad_status_remove_post_status_and_more'),
        ('clustering', '0003_modeloentrenado_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='modelo_clustering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clustering.modeloentrenado'),
        ),
    ]
