# Generated by Django 5.1.5 on 2025-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_campaign_campaign_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.DeleteModel(
            name='AddSet',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
