# Generated by Django 5.1.5 on 2025-05-23 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_vacante_modelo_clustering'),
        ('clustering', '0007_alter_clustertargeting_age_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adset',
            name='targeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clustering.clustertargeting'),
        ),
    ]
