# Generated by Django 5.1.5 on 2025-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_delete_add_delete_addset_campaign_campaign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('adset_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('creative', models.CharField(max_length=250)),
                ('access_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=250)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_event', models.CharField(blank=True, choices=[('IMPRESSIONS', 'CPM (POr cada 1000 impresiones)'), ('CLICKS', 'CPC (Por cada click)'), ('LINK_CLICKS', 'Clicks en enlaces específicos'), ('POST_ENGAGEMENT', 'Interacciones'), ('VIDEO_VIEWS', 'Vistas de video')], default='REACH', max_length=250)),
                ('optimization_goal', models.CharField(blank=True, choices=[('IMPRESSIONS', 'Conversiones'), ('REACH', 'Alcance'), ('POST_ENGAGEMENT', 'Engagement con el post'), ('VIDEO_VIEWS', 'Vistas'), ('IMPRESSIONS', 'Impresiones'), ('LEAD_GENERATION', 'Leads'), ('CONVERSIONS', 'Conversiones'), ('VALUE', 'Value'), ('LANDING_PAGE_VIEWS', 'Landing page')], default='REACH', max_length=250)),
                ('status', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=100)),
                ('addset_id', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='budget',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, choices=[('CONVERSIONS', 'Conversiones'), ('ENGAGEMENT', 'Interacción'), ('BRAND_AWARENESS', 'Conocimiento de marca'), ('LEAD_GENERATION', 'Leads')], default='REACH', max_length=250),
        ),
    ]
