# Generated by Django 5.1.5 on 2025-03-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_remove_adset_access_token_adset_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adset',
            name='addset_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
