# Generated by Django 5.1.5 on 2025-03-26 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_alter_adset_addset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='add_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ad',
            name='red_social',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('X', 'X')], default='facebook', max_length=20),
        ),
        migrations.AlterField(
            model_name='adset',
            name='billing_event',
            field=models.CharField(blank=True, choices=[('IMPRESSIONS', 'CPM (Por cada 1000 impresiones)'), ('CLICKS', 'CPC (Por cada click)'), ('LINK_CLICKS', 'Clicks en enlaces específicos'), ('POST_ENGAGEMENT', 'Interacciones'), ('VIDEO_VIEWS', 'Vistas de video')], default='REACH', max_length=250),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='red_social',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('X', 'X')], default='facebook', max_length=20),
        ),
    ]
