# Generated by Django 5.1.5 on 2025-04-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_ad_add_id_ad_created_at_ad_red_social_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='add_id',
            new_name='ad_id',
        ),
        migrations.RenameField(
            model_name='adset',
            old_name='addset_id',
            new_name='adset_id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='creative',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
