# Generated by Django 5.1.5 on 2025-04-05 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_rename_add_id_ad_ad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('object_story_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('call_to_action', models.CharField(choices=[('LEARN_MORE', 'Más información'), ('SIGN_UP', 'Registrarse'), ('SHOP_NOW', 'Comprar ahora'), ('CONTACT_US', 'Contáctanos'), ('SUBSCRIBE', 'Suscribirse'), ('GET_OFFER', 'Obtener oferta')], max_length=50)),
                ('creative_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='adset_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adset',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('CONVERSIONS', 'Conversiones'), ('ENGAGEMENT', 'Interacción'), ('BRAND_AWARENESS', 'Conocimiento de marca'), ('LEAD_GENERATION', 'Leads')], default='REACH', max_length=250),
        ),
    ]
