# Generated by Django 5.1.5 on 2025-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_creative_alter_ad_adset_id_alter_adset_daily_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creative',
            old_name='video_url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='creative',
            name='name',
            field=models.CharField(default='un name default', max_length=255),
            preserve_default=False,
        ),
    ]
