# Generated by Django 5.1.5 on 2025-04-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_rename_video_url_creative_link_creative_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='object_story_id',
        ),
    ]
