# Generated by Django 5.1.5 on 2025-04-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_remove_creative_object_story_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='creative',
        ),
        migrations.AddField(
            model_name='ad',
            name='creative_id',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
