# Generated by Django 5.1.5 on 2025-04-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_remove_ad_access_token_alter_ad_adset_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='hashtags',
        ),
    ]
