# Generated by Django 5.1.6 on 2025-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_remove_campaign_formato_remove_campaign_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='comentario_admin',
            field=models.TextField(blank=True, help_text='Comentario del administrador al aprobar o rechazar', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', help_text='Estado del anuncio', max_length=20),
        ),
    ]
