# Generated by Django 5.1.6 on 2025-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_ad_comentario_admin_ad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
