# Generated by Django 5.1.5 on 2025-04-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_ad_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='red_social',
        ),
    ]
