# Generated by Django 5.1.6 on 2025-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_ad_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacante', models.CharField(max_length=255)),
                ('empresa', models.TextField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('contrato', models.CharField(max_length=100)),
                ('salario', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
