# Generated by Django 5.1.5 on 2025-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_remove_campaign_red_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('CONVERSIONS', 'Conversiones'), ('EVENT_RESPONSES', 'Respuesta a eventos'), ('LINK_CLICKS', 'Link clics'), ('REACH', 'Alcance'), ('BRAND_AWARENESS', 'Conocimiento de marca'), ('LEAD_GENERATION', 'Leads')], default='REACH', max_length=250),
        ),
    ]
